title: Accordion Heaven
author: Gene Babon
email: gene@genebabon.com
description: > # this means to ignore newlines until "baseurl:"
  Accordions rock!  Just mention the word "accordion" and people will begin to smile.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
